language: python

sudo: required

python:
  - 3.5

services:
  - docker

env:
  # cibuildwheel for 3.5+ only
  - CIBW_SKIP="cp27-* cp33-* cp34-*"

install:
  - python -m pip install codecov
  - python setup.py install

script:
  - coverage run run_tests.py
  - python -m pip install cibuildwheel~=0.7.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: "sdist"
  user:
    secure: "As8AEyc8CZD3pD7EKtlTXC1aDucm2Sr7DtpW4hRI+PxlfeHCd/b1rkgDygfpDT01sT7tNIwkcnl1ElUrPLMTWJwpumnKyybdUKZ2R3y+ACiAjZZkBiXzI1TQr0MEjdyrFnAgRKMFWvT5O0hCj03BUsAms2vjAir458fszgaPXqdDH+g6JpXGOiVejf853N4ZZ30RoaWAL8p7PoJu55mROcuxISW0e/XcxrbkK1kZv/Ceg2OwbFCONLmno8eXMH3vx1c5hLoGkxzXFjeF2Vk9Xy9+fFkC+Zw/DbX3L+fMXQORVslGs+A+CjO4xRr/cAge/H1ntk+1GYe2hX43D6Y9OEEV7/HB+RpYIkALf2tkohqCfO4lm9CGGoU2Y9v3DNm2Hm8xCH9BwuBf6TPoQ5XUKiu7JV9UbWsa187eD1keg/hEo1E4oWp4SV36o1NX2MeQqyfCdeOUtYEhg5Yy9WMY3AgoZ0/a6lWo3xsYLgickIXl0NO0I0tL4RazOSQ5yvGNHpG7GGNCbEJEMwud+wum9tQgs5+6W1c/mn0XxEm7Z+YYES9h216XjKkvsGk5n4rxDKc/hWNXxt3WQKnLuL3L507aBj141wh37z8TfuDoI56COCBl5X1klJSAdVxIT6m+LuMKMKelJ3JHz2x5k4Nuh16PAne6YEy8RyV1lr0hkJA="
  password:
    secure: "Q+Su4CsOd0RQAPZdDgL53McJxQrO/dpH/jMpdugKoZWyi13DLPZ/o7t59JwgnQZSxH9nMXLpWCH8jHYagZOmwliz5d4zucPrvNG9+qQXKWWY+yBTnV2OlxATeClznejTOShNf8oWHcBZOfTM4Jvs5sWpgxle1BjWDwD1usAxNIoif/XjQsN4Lg8A1EvQ6zfne0yxEwyLuuyd4pO0Akroa7LRH9KLyc6wwxRaNg3kbxpHI68LUD2LvLGj+GpE7SsOpj4vOKub/gSk43zl6/7b4iDLWgqvLGQ+bhU3QqtCQJ4L+nWADxBf98wvtTlMcm5wqgXC3N1bkaTGta6PfLsde2Rl5hJpjJHvk2oRh7gPYVJYqKU4al9y0hnpylSAnY6IfQXT/hVqeQfW/o4s17jHHs0/tp4qD3ZvaYfkI9zuqqNMKWWHNaIUoAF1nvVcZotoLVTCbxNJ9GIe+5E/YbeZWI3fczoCFZgDcDpZDMQXA9yf7CVNsN/qnIJEyarXpKHQGMt6k708IZeA6hkof+i7apo4IAyTxIjmG2PWe/IdHkvBB6deZlDURmlC7nmWuJd7hYTj+atfJIrvfgpErzSh5zYB14aO5UzQaml+K7eblg36iFKfapwDREjqn85WZAwz95yyx9V9Ar/nD7A6Wp45bzh+H9tHlsxh9u0QOwNWN+E="
  on:
    tags: true

