environment:
  matrix:
    - PYTHON: "C:\\Python35"
      WHEEL_DIR: "whl35"
    - PYTHON: "C:\\Python35-x64"
      WHEEL_DIR: "whl35-64"
    - PYTHON: "C:\\Python36"
      WHEEL_DIR: "whl36"
    - PYTHON: "C:\\Python36-x64"
      WHEEL_DIR: "whl36-64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python --version"
  - "%CMD_IN_ENV% python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% pip install --disable-pip-version-check --user --upgrade pip"

build_script:
  - "%CMD_IN_ENV% pip install wheel twine"
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python -m twine upload %WHEEL_DIR%/*.whl"
  #- |
  #  if [[ $TRAVIS_TAG ]]; then
  #    %CMD_IN_ENV% python -m pip install wheel twine
  #    %CMD_IN_ENV% python -m twine upload wheelhouse/*.whl
  #  fi