environment:
  matrix:
    - PYTHON: "C:\\Python35"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip install --disable-pip-version-check --user --upgrade pip

build_script:
  - pip install wheel twine
  #- python setup.py bdist_wheel
  #- twine upload dist/*.whl"
  #- |
  #  if [[ $TRAVIS_TAG ]]; then
  #    %CMD_IN_ENV% python -m pip install wheel twine
  #    %CMD_IN_ENV% python -m twine upload wheelhouse/*.whl
  #  fi