environment:
  global:
    TWINE_USERNAME:
      secure: I6Y7b3rA208f0/3wf+P4ng==
    TWINE_PASSWORD:
      secure: HDGwpd7/c+jvca0bZFxvy5rd6xoL5veSYqW3Cdqui3M=

  matrix:
    - PYTHON: "C:\\Python35"
      WHEEL_DIR: "whl35"
    - PYTHON: "C:\\Python35-x64"
      WHEEL_DIR: "whl35-64"
    - PYTHON: "C:\\Python36"
      WHEEL_DIR: "whl36"
    - PYTHON: "C:\\Python36-x64"
      WHEEL_DIR: "whl36-64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
  - echo %TWINE_USERNAME%
  - pip install wheel twine
  - python setup.py bdist_wheel
  - twine upload dist/*.whl
  #- >
  #  IF "%APPVEYOR_REPO_TAG%" == "true"
  #  (
  #  pip install wheel twine
  #  &&
  #  python setup.py bdist_wheel
  #  &&
  #  twine upload dist/*.whl
  #  )