environment:
  # wheels for 3.5+ only
  CIBW_SKIP: "cp2* cp33-* cp34-*"

build_script:
  - pip install cibuildwheel~=0.7.1
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )