environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    pip install wheel twine
    &&
    python setup.py bdist_wheel
    &&
    twine upload dist/*.whl
    )