environment:
  CIBW_SKIP: cp2* cp33-* cp34-*

install:
  - cmd: python -m pip install cibuildwheel==0.7.1
build_script:
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing wheelhouse/*.whl"
      }