build_script:
  - set PYTHON=C:\Python36
  - set PATH=%PYTHON%;%PATH%
  - set CIBW_SKIP=cp2* cp33-* cp34-*
  - where python
  - where pip
  - echo %PATH%
  - python -m pip install cibuildwheel~=0.7.1
  - python -m cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )