environment:
  CIBW_SKIP: cp2* cp33-* cp34-*

build_script:
  - pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }
