build_script:
  - set CIBW_SKIP=cp2* cp33-* cp34-*
  - C:\Python36\python.exe -m pip install cibuildwheel~=0.7.1
  - C:\Python36\python.exe -m cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    C:\Python36\python.exe -m pip install twine
    &&
    C:\Python36\python.exe -m twine upload wheelhouse/*.whl
    )